
server:
  port: 8080

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/utteok?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
#   url=jdbc:mariadb://<DB ??>:<?? ??>/<DatabaseName>
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
mybatis:
#  type-aliases-package: com.example.demo.mvc.**.vo  # entity? ???? ????.
  mapper-locations: mybatis/**/*.xml                  # XmlMapper.xml? ???? ????.

api:
  upload:
    dir:
      RV0010: C:\Users\Hwang\Desktop\upload\review

user:
  home: