server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
    import: app_local.yml
  datasource:  # ** 실서버에 업데이트 반영됨 환경 분리 필요 **
    url: jdbc:log4jdbc:mariadb://localhost:3306/utteok?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    #   url=jdbc:mariadb://<DB ??>:<?? ??>/<DatabaseName>
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

mybatis:
  mapper-locations: mybatis/**/*.xml

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
    import: app_prod.yml
  datasource:
    url: jdbc:log4jdbc:mariadb://118.67.132.171:3306/utteok?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: utteok
    password: halfandhalf401!!
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

mybatis:
  mapper-locations: mybatis/**/*.xml
