spring:
  profiles:
  include: private

jwt:
  secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K

oauth:
  kakao:
    client-id: 0bc522cade9c019a689ccfb2e8fbdc2a
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: W_2DmcLfYU
    client-id: Y2i4SlApP7A1KZsUoott
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com



#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 앱 설정 -> 앱 키 -> REST API 키
#            client-secret: 제품 설정 -> 카카오 로그인 -> 보안 -> Client Secret
#            redirect-uri: 앱 설정 -> 플랫폼 -> Web // http://localhost:8080/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST
#            client-name: Kakao
#            scope:
#              - 제품 설정 -> 카카오 로그인 -> 동의 항목
#              - profile_nickname
#              - profile_image
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id